/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An more detailed EniroPro company advert.
type EniroProCompanyDetails struct {
	PublicListings []PublicListing `json:"publicListings,omitempty"`
	// Country of origin for for this industry facts. A two letter uppercase ISO 3166-1-alpha-2 country code.
	Country string `json:"country,omitempty"`
	// The data source of this company. Known values are CUSTOMER, for paying customers. LEGAL for an external source like  a official register.
	DataSource string `json:"dataSource,omitempty"`
	// Norwegian ONLY
	DnSideboardUrl string `json:"dnSideboardUrl,omitempty"`
	// Norwegian ONLY
	DnTopboardUrl string `json:"dnTopboardUrl,omitempty"`
	// The search related keywords associated with this company.
	Keywords []string `json:"keywords,omitempty"`
	// If record represents suboffice
	Suboffice bool `json:"suboffice,omitempty"`
	// A textual description of the warranties that a company offers.
	WarrantiesDescription string `json:"warrantiesDescription,omitempty"`
	// External links.
	ExternalLinks []ExternalLink `json:"externalLinks,omitempty"`
	// Web shop URL.
	WebshopUrl string `json:"webshopUrl,omitempty"`
	Brochure *Brochure `json:"brochure,omitempty"`
	// A certificate that this company has.
	Certifications []Certification `json:"certifications,omitempty"`
	// A contact person for a company.
	ContactPersons []ContactPerson `json:"contactPersons,omitempty"`
	// A contact form URL for a company.
	ContactFormUrl string `json:"contactFormUrl,omitempty"`
	Dealers *Dealers `json:"dealers,omitempty"`
	Distributors *Distributors `json:"distributors,omitempty"`
	// Meta information about an image.
	Images []Image `json:"images,omitempty"`
	Listing *Listing `json:"listing,omitempty"`
	MediaLinks *SocialMediaLinks `json:"mediaLinks,omitempty"`
	// An Office of a company.
	Offices []Office `json:"offices,omitempty"`
	OpeningHours *OpeningHours `json:"openingHours,omitempty"`
	ReferenceCustomers *ReferenceCustomers `json:"referenceCustomers,omitempty"`
	References *References `json:"references,omitempty"`
	RegisterListing *RegisterCompany `json:"registerListing,omitempty"`
	RegisterOwnListing *RegisterCompanyDetails `json:"registerOwnListing,omitempty"`
	// An industry to which companies are related, with additional customer specific data
	SubIndustries []EniroProCompanyIndustry `json:"subIndustries,omitempty"`
	// A block of text describing aspects of the company.
	TextBlocks []TextBlock `json:"textBlocks,omitempty"`
	// A trade this company is involved with. A trade could for example be manufacturing, service providing or consulting.
	Trades []Trade `json:"trades,omitempty"`
	// Type of advert this company listing is.
	AdvertType string `json:"advertType,omitempty"`
	// Company business unit ID (DK only).
	BusinessUnitId string `json:"businessUnitId,omitempty"`
	// Company Id
	CompanyId string `json:"companyId,omitempty"`
	// The company customer id.
	CustomerId string `json:"customerId,omitempty"`
	// A promotional description of the company.
	Description string `json:"description,omitempty"`
	// Company main email.
	Email string `json:"email,omitempty"`
	// Company main internet home page.
	HomePage string `json:"homePage,omitempty"`
	// The unique Norwegian id for this company.
	LineId string `json:"lineId,omitempty"`
	// The id of the listing this company belongs to.
	ListingId string `json:"listingId,omitempty"`
	// The Type of this company listing.
	ListingType string `json:"listingType,omitempty"`
	// Central Business Register (Denmark) marked company as protected against being contacted for advertisement purpose  Applicable only for Denmark.
	MarketingProtection bool `json:"marketingProtection,omitempty"`
	// Company name.
	Name string `json:"name,omitempty"`
	// Company organisation number.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	// Company secret organisation number.  Companies may have a secret/private organisation number;  e.g. Swedish ENK.
	SOrganisationNumber string `json:"sOrganisationNumber,omitempty"`
	// The rank of this company in the context of a search result.
	Rank float64 `json:"rank,omitempty"`
	// Sales rank reflects the amount of purchases for this company. High rank means high amount.
	SalesRank int64 `json:"salesRank,omitempty"`
	CurrentIndustry *EniroProIndustry `json:"currentIndustry,omitempty"`
	Link *Link `json:"link,omitempty"`
	// An industry to which companies are related, with additional customer specific data
	Industries []EniroProCompanyIndustry `json:"industries,omitempty"`
	Location *Location `json:"location,omitempty"`
	MainImage *Image `json:"mainImage,omitempty"`
	PhoneNumbers *TelephoneNumbers `json:"phoneNumbers,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
	// A paid product for this company.
	Products []Product `json:"products,omitempty"`
	ReferenceTexts *ReferenceTexts `json:"referenceTexts,omitempty"`
	// A search ad image associated with an company.
	SearchAdImages []SearchAdImage `json:"searchAdImages,omitempty"`
	VisitorAddress *Address `json:"visitorAddress,omitempty"`
}
