/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// EniroProLocation
type EniroProLocation struct {
	// Location country ID.
	CountryId string `json:"countryId,omitempty"`
	// The unique id identifying this location.
	Id string `json:"id,omitempty"`
	// Location type.
	LocationType string `json:"locationType,omitempty"`
	// Location name.
	Name string `json:"name,omitempty"`
	// parent ID.
	ParentId string `json:"parentId,omitempty"`
	// Child locations. Circular relationship.
	Children []EniroProLocation `json:"children,omitempty"`
}
