/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Information about a company's opening hours. Contains a textual description and/or detailed information for each day of the week.
type OpeningHours struct {
	// An Office of a company.
	Description string `json:"description,omitempty"`
	Friday *DayOpeningHours `json:"friday,omitempty"`
	Monday *DayOpeningHours `json:"monday,omitempty"`
	Saturday *DayOpeningHours `json:"saturday,omitempty"`
	Sunday *DayOpeningHours `json:"sunday,omitempty"`
	Thursday *DayOpeningHours `json:"thursday,omitempty"`
	Tuesday *DayOpeningHours `json:"tuesday,omitempty"`
	Wednesday *DayOpeningHours `json:"wednesday,omitempty"`
}
