/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A particular proposal for some input term. The suggestion value can be a the suggestion for any type of query for example a company or person name.
type Suggestion struct {
	// The actual proposed suggestion.
	Value string `json:"value,omitempty"`
}
