/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A contact person for a company.
type ContactPerson struct {
	// The email of the company contact person
	Email string `json:"email,omitempty"`
	// The name of the company's contact person.
	Name string `json:"name,omitempty"`
	// The role the contact person has in the company.
	Role string `json:"role,omitempty"`
	// The role code the contact person has in the company.
	RoleCode string `json:"roleCode,omitempty"`
	// The telephone number of the company contact person
	TelephoneNumber string `json:"telephoneNumber,omitempty"`
}
