/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A role a person has in a register company.
type RegisterPersonRole struct {
	// The birth date of the person who has this role. On standard ECS format.
	BirthDate string `json:"birthDate,omitempty"`
	// The name of the entity that elected this role.
	Elector string `json:"elector,omitempty"`
	// The name of the entity that has this role.
	Name string `json:"name,omitempty"`
	// Person Id
	PersonId string `json:"personId,omitempty"`
	// The responsibility of this role.
	Responsibility string `json:"responsibility,omitempty"`
	// The title of the role.
	Title string `json:"title,omitempty"`
	// The title code of the role.
	TitleCode string `json:"titleCode,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
	Details *Link `json:"details,omitempty"`
}
