/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Pagination information for a page in a list of data.
type Pagination struct {
	// The currently requested page.
	CurrentPage int32 `json:"currentPage,omitempty"`
	// Total number of available pages for the current list.
	NumberOfAvailablePages int32 `json:"numberOfAvailablePages,omitempty"`
	// Total number of results listed on the page.
	PageSize int32 `json:"pageSize,omitempty"`
	// An Atom-style link that describes the relationships between resources.
	NearbyPages []PageLink `json:"nearbyPages,omitempty"`
	Next *PageLink `json:"next,omitempty"`
	Previous *PageLink `json:"previous,omitempty"`
	Sorting *Sorting `json:"sorting,omitempty"`
}
