/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An industry, any department or branch of art, occupation or business.
type EniroProIndustryFacts struct {
	// The category type this industry belongs to.  Possible values:  <value>TOPCATEGORY</value>  ,  <value>CATEGORY</value>  ,  <value>MAIN</value>  ,  <value>SPECIALITY</value>
	CategoryType string `json:"categoryType,omitempty"`
	// Country of origin for for this industry facts. A two letter uppercase ISO 3166-1-alpha-2 country code.
	Country string `json:"country,omitempty"`
	// Industry description
	Description string `json:"description,omitempty"`
	// Industry Code
	IndustryCode string `json:"industryCode,omitempty"`
	// The official name of the industry. E.g. \"Hairdresser\".
	Name string `json:"name,omitempty"`
	// Number of companies in this industry.
	NumberOfCompanies int32 `json:"numberOfCompanies,omitempty"`
	// An industry, any department or branch of art, occupation or business.
	Children []EniroProIndustry `json:"children,omitempty"`
	Link *Link `json:"link,omitempty"`
	// Annual financial info for an attribute of an industry.
	FinancialInfo []FinancialInfo `json:"financialInfo,omitempty"`
	// Parent industries. Circular relationship.
	Parents []EniroProIndustry `json:"parents,omitempty"`
	// An top employer in an industry. A company that is among the ones with the most employees in the industry.
	TopEmployeesCompanies []TopEmployeesCompany `json:"topEmployeesCompanies,omitempty"`
	// An top employer in an industry. A company that is among the ones with the most employees in the industry.
	TopTurnoverCompany []TopTurnoverCompany `json:"topTurnoverCompany,omitempty"`
	Companies *Link `json:"companies,omitempty"`
}
