/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

type KeyFigures struct {
	BusinessCategoryRatingSdi int32 `json:"businessCategoryRatingSdi,omitempty"`
	BusinessCategoryRatingEmployees int32 `json:"businessCategoryRatingEmployees,omitempty"`
	NumberOfCompaniesInBusinessCategory int32 `json:"numberOfCompaniesInBusinessCategory,omitempty"`
	CountyRatingSdi int32 `json:"countyRatingSdi,omitempty"`
	CountyRatingEmployees int32 `json:"countyRatingEmployees,omitempty"`
	NumberOfCompaniesInCountyAccounting int32 `json:"numberOfCompaniesInCountyAccounting,omitempty"`
	NumberOfCompaniesInCountyEmployees int32 `json:"numberOfCompaniesInCountyEmployees,omitempty"`
	MunicipalityRatingSdi int32 `json:"municipalityRatingSdi,omitempty"`
	MunicipalityRatingEmployees int32 `json:"municipalityRatingEmployees,omitempty"`
	NumberOfCompaniesInMunicipalityAccounting int32 `json:"numberOfCompaniesInMunicipalityAccounting,omitempty"`
	NumberOfCompaniesInMunicipalityEmployees int32 `json:"numberOfCompaniesInMunicipalityEmployees,omitempty"`
}
