/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Filter group. The display name is a common description for all the filters in the group. I.e. if the display name in the filter group is: 'Countrypart' then you can expect all filters to represent a particular country part like: Nord-Norge (North of Norway) or Vestlandet.
type FilterGroup struct {
	// a descriptive name of something that all filters in this group is a specialisation of.
	DisplayName string `json:"displayName,omitempty"`
	// the type identifier for this filter group. E.g. 'fxcountrypart'. All filters in this group will be of this type.
	FilterType string `json:"filterType,omitempty"`
	// the name of this filter group, e.g. 'fxbccodedeepnavigator'. This is sometimes necessary to distinguish between filter groups with the same type.
	Name string `json:"name,omitempty"`
	// A filter that will produce a subset of a list.
	Filters []Filter `json:"filters,omitempty"`
	Removed *Link `json:"removed,omitempty"`
}
