/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Details for a publicly listing
type PublicListing struct {
	// Company country
	CompanyCountry string `json:"companyCountry,omitempty"`
	// Ticker
	Ticker string `json:"ticker,omitempty"`
	// Stock Exchange
	StockExchange string `json:"stockExchange,omitempty"`
	// Listing date
	ListingDate string `json:"listingDate,omitempty"`
	// Company Name
	CompanyName string `json:"companyName,omitempty"`
	// ISIN for stock
	Isin string `json:"isin,omitempty"`
}
