/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A line of free text associated with content in a listing node. The type field suggests where the text should be  displayed in relation to the other content of the listing node.
type ListingTextLine struct {
	// Line of free text associated with a listing node.
	Text string `json:"text,omitempty"`
	// The type of freeText. Suggests where the text should be displayed in relation to the other content of the listing  node. Possible values:  - COMPANY_NAME_SUFFIX The text should be displayed behind the company name.  - PREFIX The text should be in-front of the phone number/email/homepage.  - ADDRESS_SUFFIXThe text should be displayed after an address.  Possible values:  <value>COMPANY_NAME_SUFFIX</value>  ,  <value>PREFIX</value>  ,  <value>ADDRESS_SUFFIX</value>
	Type_ string `json:"type,omitempty"`
}
