/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An annual state for a company or an enterprise.
type AnnualMain struct {
	// The code for the account being incomplete
	AccIncompleteCode string `json:"accIncompleteCode,omitempty"`
	// The comment description for the account being incomplete
	AccIncompleteDesc string `json:"accIncompleteDesc,omitempty"`
	// Auditor clarification comment
	AuditorClarificationComment string `json:"auditorClarificationComment,omitempty"`
	// Auditor name
	AuditorName string `json:"auditorName,omitempty"`
	// Auditor company id
	AuditorCompanyId int32 `json:"auditorCompanyId,omitempty"`
	// Auditors comment
	AuditorComment string `json:"auditorComment,omitempty"`
	// Auditor Liquidation Settlement
	AuditorLiquidationSettlement bool `json:"auditorLiquidationSettlement,omitempty"`
	// Compensation to CEO that is not salary
	CeoSalOtherComp bool `json:"ceoSalOtherComp,omitempty"`
	// Clarification 1
	Clarification1 bool `json:"clarification1,omitempty"`
	// Clarification 2
	Clarification2 bool `json:"clarification2,omitempty"`
	// Clarification 3
	Clarification3 bool `json:"clarification3,omitempty"`
	// Clarification 4
	Clarification4 bool `json:"clarification4,omitempty"`
	// Clarification 5
	Clarification5 bool `json:"clarification5,omitempty"`
	// Clarification 6
	Clarification6 bool `json:"clarification6,omitempty"`
	// Clarification 7
	Clarification7 bool `json:"clarification7,omitempty"`
	// Clarification 8
	Clarification8 bool `json:"clarification8,omitempty"`
	// Clarification 9
	Clarification9 bool `json:"clarification9,omitempty"`
	// Clarification 10
	Clarification10 bool `json:"clarification10,omitempty"`
	// Clarification 14
	Clarification14 bool `json:"clarification14,omitempty"`
	// Clarification 15
	Clarification15 bool `json:"clarification15,omitempty"`
	// Clarification 16
	Clarification16 bool `json:"clarification16,omitempty"`
	// Clarification 17
	Clarification17 bool `json:"clarification17,omitempty"`
	// Clarification 18
	Clarification18 bool `json:"clarification18,omitempty"`
	// Compensation Package
	CompensationPackage bool `json:"compensationPackage,omitempty"`
	// The code for the currency the account amounts are in.
	Currency string `json:"currency,omitempty"`
	// Disclamer 1
	Disclamer1 bool `json:"disclamer1,omitempty"`
	// Disclamer 2
	Disclamer2 bool `json:"disclamer2,omitempty"`
	// Disclamer 3
	Disclamer3 bool `json:"disclamer3,omitempty"`
	// Disclamer 4
	Disclamer4 bool `json:"disclamer4,omitempty"`
	// Disclamer 5
	Disclamer5 bool `json:"disclamer5,omitempty"`
	// Disclamer 6
	Disclamer6 bool `json:"disclamer6,omitempty"`
	// Disclamer 7
	Disclamer7 bool `json:"disclamer7,omitempty"`
	// Disclamer 8
	Disclamer8 bool `json:"disclamer8,omitempty"`
	// Disclamer 9
	Disclamer9 bool `json:"disclamer9,omitempty"`
	// Disclamer 10
	Disclamer10 bool `json:"disclamer10,omitempty"`
	// Disclamer 11
	Disclamer11 bool `json:"disclamer11,omitempty"`
	// Disclamer 12
	Disclamer12 bool `json:"disclamer12,omitempty"`
	// Disclamer 13
	Disclamer13 bool `json:"disclamer13,omitempty"`
	// Disclamer 14
	Disclamer14 bool `json:"disclamer14,omitempty"`
	// Disclamer 15
	Disclamer15 bool `json:"disclamer15,omitempty"`
	// Disclamer 17
	Disclamer17 bool `json:"disclamer17,omitempty"`
	// Disclamer 18
	Disclamer18 bool `json:"disclamer18,omitempty"`
	// Disclamer 19
	Disclamer19 bool `json:"disclamer19,omitempty"`
	// Employees
	Employees int32 `json:"employees,omitempty"`
	// Company's equity is less than 50% of the called up share capital
	EquityLessThanFiftyPercentShare bool `json:"equityLessThanFiftyPercentShare,omitempty"`
	// Equity loss
	EquityLoss bool `json:"equityLoss,omitempty"`
	// GivenLoanConf87
	GivenLoanConf87 bool `json:"givenLoanConf87,omitempty"`
	// HaveOtpNoNumbers
	HaveOtpNoNumbers bool `json:"haveOtpNoNumbers,omitempty"`
	// Accounting reported period. Number of months.
	Length string `json:"length,omitempty"`
	// LimitedOperation
	LimitedOperation bool `json:"limitedOperation,omitempty"`
	// LiquidationAccounting
	LiquidationAccounting bool `json:"liquidationAccounting,omitempty"`
	// ManLabourYear
	ManLabourYear float64 `json:"manLabourYear,omitempty"`
	// NoOperation
	NoOperation bool `json:"noOperation,omitempty"`
	// NotDutyOtp
	NotDutyOtp bool `json:"notDutyOtp,omitempty"`
	// OperationsConsideredNotPresent
	OperationsConsideredNotPresent bool `json:"operationsConsideredNotPresent,omitempty"`
	// OptionsBonus
	OptionsBonus bool `json:"optionsBonus,omitempty"`
	// PartTimeEmployees
	PartTimeEmployees float64 `json:"partTimeEmployees,omitempty"`
	// Accounting reported period. (year and month YYYY-MM format)
	Period string `json:"period,omitempty"`
	// Share Fifty Percent Loss
	ShareFiftyPercentLoss bool `json:"shareFiftyPercentLoss,omitempty"`
	// ShareLoss
	ShareLoss bool `json:"shareLoss,omitempty"`
	// ShareTwoThirdsLoss
	ShareTwoThirdsLoss bool `json:"shareTwoThirdsLoss,omitempty"`
	// UnderLiquidation
	UnderLiquidation bool `json:"underLiquidation,omitempty"`
	// The year this annual info is for.
	Year int32 `json:"year,omitempty"`
}
