/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Filter
type Filter struct {
	// a descriptive name of something that all filters in this group is a specialization of.
	DisplayName string `json:"displayName,omitempty"`
	// the number of elements this filter will yield.
	Hits int64 `json:"hits,omitempty"`
	Link *Link `json:"link,omitempty"`
}
