/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// References of the company
type References struct {
	// The information url of the company
	InformationUrl string `json:"informationUrl,omitempty"`
	// Reference of the company
	ReferencesList []Reference `json:"referencesList,omitempty"`
}
