/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Professional with business roles in companies and connections to other professionals in the enterprise world.  Roles can typically be: Chairman, committee member, deputy committee member or shareholder (Daglig Leder,  Styreformann, Styremedlem, Varamedlem, Aksjon�r). A business connection is a connection between this business person to  other businesses persons.
type BusinessPerson struct {
	// The business persons age.
	Age int32 `json:"age,omitempty"`
	// Number of business person association.
	AssociatedCount int32 `json:"associatedCount,omitempty"`
	// ECO Eniro common identity for the person. May be null, if unknown.
	EcoId int32 `json:"ecoId,omitempty"`
	// The gender of the person in a abbreviation form: \"K\" (female) or \"M\" (male)
	Gender string `json:"gender,omitempty"`
	// The full name of the person.
	Name string `json:"name,omitempty"`
	// The number of business persons associated with this person.
	NumberOfRoles int32 `json:"numberOfRoles,omitempty"`
	// Id of the person
	PersonId string `json:"personId,omitempty"`
	// This persons year of birth.
	YearOfBirth int32 `json:"yearOfBirth,omitempty"`
	// Connection between 2 persons.
	Connections []Connection `json:"connections,omitempty"`
	Link *Link `json:"link,omitempty"`
	// An industry a person has roles in.
	IndustryConnections []IndustryConnection `json:"industryConnections,omitempty"`
	Location *Location `json:"location,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
	// Person role in a company.
	Roles []Role `json:"roles,omitempty"`
	VisitorAddress *Address `json:"visitorAddress,omitempty"`
}
