/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// The distributors for the company
type Distributors struct {
	// The information Url of the company
	InformationUrl string `json:"informationUrl,omitempty"`
	// The distributor for the company
	DistributorArray []Distributor `json:"distributorArray,omitempty"`
}
