/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Meta information about an image.
type Image struct {
	// Identifier (id, url, filename etc. depending on context) for this image.
	Identifier string `json:"identifier,omitempty"`
	// A text associated with this image.
	Text string `json:"text,omitempty"`
	// Image URL
	Url string `json:"url,omitempty"`
}
