/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Information about a company's reference customers.
type ReferenceCustomers struct {
	// A url to information about the reference customers of a company.
	InformationUrl string `json:"informationUrl,omitempty"`
	// Get a list of the names of the reference customers of a company.
	ReferenceCustomerNames []string `json:"referenceCustomerNames,omitempty"`
}
