/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A business person available for a business network search
type NetworkCandidatePerson struct {
	// ECO Eniro common identity for the person. May be null, if unknown.
	EcoId int32 `json:"ecoId,omitempty"`
	// The gender of the person in a abbreviation form: \"K\" (female) or \"M\" (male)
	Gender string `json:"gender,omitempty"`
	// The full name of the person.
	Name string `json:"name,omitempty"`
	// The number of business persons associated with this person.
	NumberOfRoles int32 `json:"numberOfRoles,omitempty"`
	// Id of the person
	PersonId string `json:"personId,omitempty"`
	// This persons year of birth.
	YearOfBirth int32 `json:"yearOfBirth,omitempty"`
	Link *Link `json:"link,omitempty"`
	Location *Location `json:"location,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
	VisitorAddress *Address `json:"visitorAddress,omitempty"`
}
