/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A role a person has in a company.
type Role struct {
	// The organisation number of the associated company.
	CompanyId int64 `json:"companyId,omitempty"`
	// The complete and formal name of the company that this role belongs to.
	CompanyName string `json:"companyName,omitempty"`
	// The name of the role.
	RoleName string `json:"roleName,omitempty"`
	Company *Link `json:"company,omitempty"`
	// Annual accounts for the company. Note that only a subset of accounting posts are available, for a complete  set the company must be retrieved.
	CompanyAccounts []AnnualAccount `json:"companyAccounts,omitempty"`
}
