/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

type DateOnly struct {
	Year int32 `json:"year,omitempty"`
	Month int32 `json:"month,omitempty"`
	Day int32 `json:"day,omitempty"`
	DayOfWeek *DayOfWeek `json:"dayOfWeek,omitempty"`
	DayOfYear int32 `json:"dayOfYear,omitempty"`
	DayNumber int32 `json:"dayNumber,omitempty"`
}
