/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff
import (
	"time"
)

type ShareholderRealOwner struct {
	EniroId int64 `json:"eniroId,omitempty"`
	BirthDate time.Time `json:"birthDate,omitempty"`
	BirthYear int32 `json:"birthYear,omitempty"`
	NameFromRole string `json:"nameFromRole,omitempty"`
	NameFromShareholder string `json:"nameFromShareholder,omitempty"`
	IdentificationExplanation string `json:"identificationExplanation,omitempty"`
	ShareInPercent float64 `json:"shareInPercent,omitempty"`
	RoleEntries []RoleEntryRealOwner `json:"roleEntries,omitempty"`
	DirectOwnership bool `json:"directOwnership,omitempty"`
	IndirectOwnership bool `json:"indirectOwnership,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	Location string `json:"location,omitempty"`
	ZipCode string `json:"zipCode,omitempty"`
	Address string `json:"address,omitempty"`
}
