/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff
import (
	"time"
)

// Represents a company or person share ownership.
type Relation struct {
	// Share type. E.g.: \"A-aksjer\"
	ShareType string `json:"shareType,omitempty"`
	// Total number of shares in current company.
	TotalShares int64 `json:"totalShares,omitempty"`
	// Number of shares owned by this shareholder in current company.
	NumberOfShares int64 `json:"numberOfShares,omitempty"`
	// Share percentage owned by this shareholder in current company.
	SharePercentage float64 `json:"sharePercentage,omitempty"`
	// Indicates if ownerships are restricted to direct ownerships. [true | false]
	Direct bool `json:"direct,omitempty"`
	SourceDate float64 `json:"sourceDate,omitempty"`
	UpdateDate time.Time `json:"updateDate,omitempty"`
	// Shareholder-ID. Used when fetching more information for this shareholder.
	Id string `json:"id,omitempty"`
	// Organisation number. Only available for company shareholder.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	// Four-digit birth year. Only available for person shareholder.
	BirthYear string `json:"birthYear,omitempty"`
	// Only available for person shareholder.
	BirthDate time.Time `json:"birthDate,omitempty"`
	// Company- or person name.
	Name string `json:"name,omitempty"`
	// Shareholder address. E.g.: \"Drammensveien 1\"
	Address string `json:"address,omitempty"`
	// Shareholder postal code. E.g.: \"1234\"
	ZipCode string `json:"zipCode,omitempty"`
	// Shareholder city. E.g. \"OSLO\":
	Location string `json:"location,omitempty"`
	// Shareholder ISO2 country code. E.g.: \"NO\"
	Country string `json:"country,omitempty"`
	// Describes type of shareholder. [\"Person\" | \"Company\" | \"Unknown\"]
	EntityType string `json:"entityType,omitempty"`
}
