/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An industry to which companies are related, with additional customer specific data
type EniroProCompanyIndustry struct {
	// The unique code identifying this industry.
	Code string `json:"code,omitempty"`
	// CompanyId
	CompanyId string `json:"companyId,omitempty"`
	// Industry description
	Description string `json:"description,omitempty"`
	// The official name of the industry. E.g. \"Hairdresser\".
	Name string `json:"name,omitempty"`
	// Sales rank reflects the amount of purchases for this industry. High rank means high amount.
	SalesRank int64 `json:"salesRank,omitempty"`
	// Style of the industry representation. (ex. FRAMED, BOLD). Can be null
	Style string `json:"style,omitempty"`
}
