/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Comparison of company and industry on county- and country basis
type Analysis struct {
	Konsern int32 `json:"konsern,omitempty"`
	AccountingYear int32 `json:"accountingYear,omitempty"`
	CompanyFigures *AnalysisSection `json:"companyFigures,omitempty"`
	CountyFigures *AnalysisSection `json:"countyFigures,omitempty"`
	CountryFigures *AnalysisSection `json:"countryFigures,omitempty"`
	AsCountryFigures *AnalysisSection `json:"asCountryFigures,omitempty"`
}
