/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// The distributor for the company
type Distributor struct {
	// The name of the company
	Name string `json:"name,omitempty"`
	// The organisation number of the company
	OrgNumber string `json:"orgNumber,omitempty"`
}
