/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A trade this company is involved with. A trade could for example be manufacturing, service providing or consulting.
type Trade struct {
	// Code for the trade.
	Code string `json:"code,omitempty"`
	// Code for the trade.
	Text string `json:"text,omitempty"`
}
