/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An annual report for a company.
type AnnualReport struct {
	// report file fingerprint.
	Fingerprint string `json:"fingerprint,omitempty"`
	// report period. (year and month YYYY-MM format)
	Period string `json:"period,omitempty"`
}
