/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A block of text describing aspects of the company.
type TextBlock struct {
	// The text.
	Text string `json:"text,omitempty"`
	// Title for the text block.
	Title string `json:"title,omitempty"`
	// The type of text block.
	Type_ string `json:"type,omitempty"`
	// A text element.
	TextElements []TextElement `json:"textElements,omitempty"`
}
