/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A subsidiary of a company.
type Subsidiary struct {
	// The organisation number of this subsidiary.
	CompanyId string `json:"companyId,omitempty"`
	// The name of this subsidiary.
	Name string `json:"name,omitempty"`
	// How much the parent owns of this subsidiary
	OwnedPercentage float64 `json:"ownedPercentage,omitempty"`
	Details *Link `json:"details,omitempty"`
}
