/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Social Media links for the company
type SocialMediaLinks struct {
	// The facebook URL of the company
	FacebookUrl string `json:"facebookUrl,omitempty"`
	// The google plus URL of the company
	GooglePlusUrl string `json:"googlePlusUrl,omitempty"`
	// LinkedIn URL
	LinkedInUrl string `json:"linkedInUrl,omitempty"`
	// Twitter URL
	TwitterUrl string `json:"twitterUrl,omitempty"`
	// Youtube URL
	YoutubeUrl string `json:"youtubeUrl,omitempty"`
}
