/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Company owner response, result class containing actual owner of the company
type CompanyRealOwner struct {
	// ID of company
	CompanyId int64 `json:"companyId,omitempty"`
	// Name of the company
	Name string `json:"name,omitempty"`
	MostRecentAccountingYear int32 `json:"mostRecentAccountingYear,omitempty"`
	RequestResultId int32 `json:"requestResultId,omitempty"`
	RequestResultMessage string `json:"requestResultMessage,omitempty"`
	VisitAddress *AddressRealOwner `json:"visitAddress,omitempty"`
	PostalAddress *AddressRealOwner `json:"postalAddress,omitempty"`
	Nace *NaceRealOwner `json:"nace,omitempty"`
	Shareholders []ShareholderRealOwner `json:"shareholders,omitempty"`
}
