/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Linked list defining shortest path between two entities. Node types are typically alternating between businessperson and company since the shortest path between to business persons goes via a common company.
type BusinessNetworkConnectionNode struct {
	Company *NetworkCompany `json:"company,omitempty"`
	Person *BusinessPerson `json:"person,omitempty"`
}
