/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Reference to a on-line brochure containing information about a company
type Brochure struct {
	// A short description related to the on-line brochure.
	Description string `json:"description,omitempty"`
	// The URL to the on-line brochure.
	Url string `json:"url,omitempty"`
}
