/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Corporate structure for a company. The corporate structure is based on share-ownership, where a company is defined  as being a subsidiary if a parent company controls more than 50% of the shares (independent of share classification).
type CorporateStructure struct {
	Tree *CompanyNode `json:"tree,omitempty"`
	// Corporate account information for the parent company. Note that the structure is just a summary with a  selection of important accounting figures for the most recent years.
	CorporateAccounts []AnnualAccount `json:"corporateAccounts,omitempty"`
}
