/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Address information.
type Address struct {
	// Free text field which typically can hold Street- or road name + entrance number or postbox number, post office  name.
	AddressLine string `json:"addressLine,omitempty"`
	// Free text field that holds postbox number and post office name, if any.
	BoxAddressLine string `json:"boxAddressLine,omitempty"`
	// Post place.
	PostPlace string `json:"postPlace,omitempty"`
	// Zipcode.
	ZipCode string `json:"zipCode,omitempty"`
}
