/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// \"true\" if the company is approved by Direktoratet for byggkvalitet - \"Godkjent for ansvarsrett\" before or after 01.01.2016
type ApprovalStatus struct {
	// \"true\" if the company is approved by Direktoratet for byggkvalitet - \"Godkjent for ansvarsrett\" before or after 01.01.2016
	Approved bool `json:"approved,omitempty"`
}
