/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A list of official company types.
type RegisterCompanyType struct {
	// Country code
	CountryId string `json:"countryId,omitempty"`
	// Abbreviation for the company type, e.g. AS, AB etc.
	Id string `json:"id,omitempty"`
	// Name of the company type, e.g. \"Aksjeselskap\", \"Aktiebolag\" etc.
	Name string `json:"name,omitempty"`
}
