/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// The main office of a company that has several branches.
type MainOffice struct {
	// The organisation number of this subsidiary.
	CompanyId string `json:"companyId,omitempty"`
	// The registered name of the main office.
	Name string `json:"name,omitempty"`
	Details *Link `json:"details,omitempty"`
}
