/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Call limits
type CallLimit struct {
	// Calls allowed per minute
	PerMinute int32 `json:"perMinute,omitempty"`
	// Calls allowed per hour
	PerHour int32 `json:"perHour,omitempty"`
	// Calls allowed per day
	PerDay int32 `json:"perDay,omitempty"`
	// Calls allowed per month
	PerMonth int32 `json:"perMonth,omitempty"`
	// Calls allowed per year
	PerYear int32 `json:"perYear,omitempty"`
	// Calls allowed per period
	PerPeriod int32 `json:"perPeriod,omitempty"`
}
