/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Signature / Procuration role
type Signature struct {
	// birth date in ISO format yyyy-MM-dd
	BirthDate string `json:"birthDate,omitempty"`
	// line number in Signature right/Procuration text list
	LineNumber int32 `json:"lineNumber,omitempty"`
	// The full name of the person.
	Name string `json:"name,omitempty"`
	// role id such as SIGN, SIHV, SIFE or PROK, POHV, POFE
	RoleId string `json:"roleId,omitempty"`
	// Person Id
	PersonId string `json:"personId,omitempty"`
	Details *Link `json:"details,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
}
