/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// The opening hours of a company for a particular day.
type DayOpeningHours struct {
	// true status flag if the company is open the whole day this particular day, and false otherwise.
	AllDay bool `json:"allDay,omitempty"`
	// true status flag if the company is closed the whole day this particular day, and false otherwise.
	Closed bool `json:"closed,omitempty"`
	// The hour the company closes a particular day. Must be combined with ClosingMinutes to get a complete time.
	ClosingHour string `json:"closingHour,omitempty"`
	// The minutes the company closes a particular day. Must be combined with ClosingHour to get a complete time.
	ClosingMinutes string `json:"closingMinutes,omitempty"`
	// true status flag if the company has opening hours this particular day. Use a combination of OpeningHour +  OpeningMinutes and ClosingHour + ClosingMinutes to calculate the exact interval of the opening hours.
	OpenHours bool `json:"openHours,omitempty"`
	// The hour the company opens a particular day. Must be combined with OpeningMinutes to get a complete time.
	OpeningHour string `json:"openingHour,omitempty"`
	// The minutes the company opens a particular day. Must be combined with OpeningHour to get a complete time.
	OpeningMinutes string `json:"openingMinutes,omitempty"`
}
