/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An top employer in an industry. A company that is among the ones with the most employees in the industry.
type TopEmployeesCompany struct {
	// Internal id of the company
	CompanyId string `json:"companyId,omitempty"`
	// Name of the company
	Name string `json:"name,omitempty"`
	// Number of employees.
	NumberOfEmployees int32 `json:"numberOfEmployees,omitempty"`
	// Year for which the values of this top company is valid. In standard ECS format.
	Year string `json:"year,omitempty"`
	Details *Link `json:"details,omitempty"`
}
