/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Company that is part of a corporate structure.
type CompanyNode struct {
	// Company organisation number.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	// Company name.
	Name string `json:"name,omitempty"`
	// Company country. Uppercase ISO 3166-1-alpha-2 country code.
	CountryCode string `json:"countryCode,omitempty"`
	// Percentage of the company shares owned by it's parent.
	OwnedPercentage float64 `json:"ownedPercentage,omitempty"`
	// If a company is inactive this field has the inactivation date. ISO 8601 date format.
	InactiveDate string `json:"inactiveDate,omitempty"`
	// Companies that this company has more than 50% ownership in, e.g. subsidiaries.
	Sub []CompanyNode `json:"sub,omitempty"`
	// Annual account information for the company. Note that the structure is just a summary with a selection of important accounting figures for the most recent years.
	CompanyAccounts []AnnualAccount `json:"companyAccounts,omitempty"`
	Link *Link `json:"link,omitempty"`
}
