/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Geographical information about the company.
type Location struct {
	// Country subdivision the address is situated in.
	CountryPart string `json:"countryPart,omitempty"`
	// County description.
	County string `json:"county,omitempty"`
	// The postal municipality, district or area.
	Municipality string `json:"municipality,omitempty"`
	// Coordinate for a company.
	Coordinates []Coordinate `json:"coordinates,omitempty"`
}
