/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A connection a person has to another person
type Connection struct {
	// The gender of the person in a abbreviation form: \"K\" (female) or \"M\" (male)
	Gender string `json:"gender,omitempty"`
	// The full name of the person.
	Name string `json:"name,omitempty"`
	// The number of role connections the associated person has.
	NumberOfConnections string `json:"numberOfConnections,omitempty"`
	// Id of the person
	PersonId string `json:"personId,omitempty"`
	Link *Link `json:"link,omitempty"`
}
