/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A company with common basic information like name, address and location. Visitor- and postal addresses are optional.
type NetworkCompany struct {
	// Company business unit ID (DK only).
	BusinessUnitId string `json:"businessUnitId,omitempty"`
	// Company Id
	CompanyId string `json:"companyId,omitempty"`
	// Company main email.
	Email string `json:"email,omitempty"`
	// Company main internet home page.
	HomePage string `json:"homePage,omitempty"`
	// Central Business Register (Denmark) marked company as protected against being contacted for advertisement purpose.  Applicable only for Denmark.
	MarketingProtection bool `json:"marketingProtection,omitempty"`
	// Company name.
	Name string `json:"name,omitempty"`
	// Company organisation number.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	Link *Link `json:"link,omitempty"`
	Location *Location `json:"location,omitempty"`
	PhoneNumbers *TelephoneNumbers `json:"phoneNumbers,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
	VisitorAddress *Address `json:"visitorAddress,omitempty"`
}
