/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

type Mortgage struct {
	// Types of mortgages, Leasing (LA), factoring agreements (FA) ect.
	Type_ string `json:"type,omitempty"`
	// The group type of mortgage, Voluntary (F), Forced (T) or other (A)
	GroupType string `json:"groupType,omitempty"`
	// Name of the creditor
	Creditor string `json:"creditor,omitempty"`
	// Mortgage registration date
	Date string `json:"date,omitempty"`
	LastModified string `json:"lastModified,omitempty"`
	// The amount of the mortgage
	Amount int64 `json:"amount,omitempty"`
}
