/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An industry, any department or branch of art, occupation or business.
type EniroProIndustry struct {
	//    The category type this industry belongs to.  Possible values:  <value>TOPCATEGORY</value>,  <value>CATEGORY</value>,  <value>MAIN</value>,  <value>SPECIALITY</value>
	CategoryType string `json:"categoryType,omitempty"`
	// Industry description
	Description string `json:"description,omitempty"`
	// Industry Code
	IndustryCode string `json:"industryCode,omitempty"`
	// The official name of the industry. E.g. \"Hairdresser\".
	Name string `json:"name,omitempty"`
	// Number of companies in this industry.
	NumberOfCompanies int32 `json:"numberOfCompanies,omitempty"`
	Details *Link `json:"details,omitempty"`
	Companies *Link `json:"companies,omitempty"`
	Facts *Link `json:"facts,omitempty"`
	// Industries. Circular relationship.
	Children []Link `json:"children,omitempty"`
	// Parent industries. Circular relationship.
	Parents []Link `json:"parents,omitempty"`
}
