/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An industry a person has roles in.
type IndustryConnection struct {
	// Industry code
	IndustryCode int32 `json:"industryCode,omitempty"`
	// The name of the industry that this person has a role in.
	Name string `json:"name,omitempty"`
	Details *Link `json:"details,omitempty"`
}
