/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Details for a publicly registered company.
type RegisterCompanyDetails struct {
	// The organisation type of this company. Type codes will wary from country to country. Some examples of Norwegian  codes: \"AS\", \"ANS\", \"EP\" and \"NUF\".
	CompanyType string `json:"companyType,omitempty"`
	// The human readable company type name It should be something like Aksjeselskap for instance if the type is AS
	CompanyTypeName string `json:"companyTypeName,omitempty"`
	// Estimated turnover.
	EstimatedTurnover string `json:"estimatedTurnover,omitempty"`
	// Whether or not this company has some assets that has been used for security.  For example when acquiring a loan. null if security status is unknown.
	HasSecurity bool `json:"hasSecurity,omitempty"`
	// The names the company has had in the past.
	PreviousNames []string `json:"previousNames,omitempty"`
	// Preferred Proff listing-ID used when redirecting from register company to Proff company.
	ProffListingId string `json:"proffListingId,omitempty"`
	// Whether or not this company is registered as an enterprise.  For Norway this indicates whether or not the company is registered in \"Foretaksregisteret\".  Null if enterprise status is unknown.
	RegisteredAsEnterprise bool `json:"registeredAsEnterprise,omitempty"`
	// Whether or not this company is registered for NAV.
	RegisteredForNav bool `json:"registeredForNav,omitempty"`
	// Whether or not this company is registered for VAT.
	RegisteredForPayrollTax bool `json:"registeredForPayrollTax,omitempty"`
	// Whether or not this company is registered for VAT.
	RegisteredForVat bool `json:"registeredForVat,omitempty"`
	// VAT description, if any. Applies only to Swedish companies. E.g.: \"Ja, registrerad f�r F-skatt\".
	RegisteredForVatDescription string `json:"registeredForVatDescription,omitempty"`
	// Whether or not this company is registered for voluntary registry.
	RegisteredForVoluntary bool `json:"registeredForVoluntary,omitempty"`
	// The date the company was registered with the registry. On standard ECS format.
	RegistrationDate string `json:"registrationDate,omitempty"`
	// The share capital of this company null if not available
	ShareCapital int64 `json:"shareCapital,omitempty"`
	// Company shareholders' last updated date in YYYY-MM-DD format (ISO-8601 reduced accuracy allowed). Can be null
	ShareholdersLastUpdatedDate string `json:"shareholdersLastUpdatedDate,omitempty"`
	// Company subsidiaries' last updated date in YYYY-MM-DD format (ISO-8601 reduced accuracy allowed). Can be null
	SubsidiariesLastUpdatedDate string `json:"subsidiariesLastUpdatedDate,omitempty"`
	// The number of years this company has been in business or null if not available.
	YearsInOperation int32 `json:"yearsInOperation,omitempty"`
	// An announcement from a company.
	Announcements []Announcement `json:"announcements,omitempty"`
	// An annual account for a company or an enterprise.
	AnnualAccounts []AnnualAccount `json:"annualAccounts,omitempty"`
	// An annual report for a company.
	AnnualReports []AnnualReport `json:"annualReports,omitempty"`
	// An annual account for a company or an enterprise.
	CompanyAccounts []AnnualAccount `json:"companyAccounts,omitempty"`
	// An annual account for a company or an enterprise.
	CompanyCacheFlows []AnnualAccount `json:"companyCacheFlows,omitempty"`
	// An annual account for a company or an enterprise.
	CompanyMain []AnnualMain `json:"companyMain,omitempty"`
	// A role a company has in a register company.
	CompanyRoles  []RegisterCompanyRole `json:"companyRoles,omitempty"`
	ContactPerson *ContactPerson        `json:"contactPerson,omitempty"`
	// An annual account for a company or an enterprise.
	CorporateAccounts []AnnualAccount `json:"corporateAccounts,omitempty"`
	// An annual account for a company or an enterprise.
	CorporateCacheFlows []AnnualAccount `json:"corporateCacheFlows,omitempty"`
	// An annual account for a company or an enterprise.
	CorporateMain []AnnualMain `json:"corporateMain,omitempty"`
	MainOffice    *MainOffice  `json:"mainOffice,omitempty"`
	// A role a person has in a register company.
	PersonRoles []RegisterPersonRole `json:"personRoles,omitempty"`
	// A person that is a shareholder in a company.
	Shareholders []Shareholder `json:"shareholders,omitempty"`
	// List of Signatories
	Signatories []string `json:"signatories,omitempty"`
	// Signature roles
	SignatoryRoles []Signature `json:"signatoryRoles,omitempty"`
	// List of Procuration
	Procuration []string `json:"procuration,omitempty"`
	// Procuration roles
	ProcurationRoles []Signature `json:"procurationRoles,omitempty"`
	// A subsidiary of a company.
	Subsidiaries []Subsidiary `json:"subsidiaries,omitempty"`
	// A credit rating of a company.
	CreditRating *string `json:"creditRating,omitempty"`
	// An analysis of a company
	Analyses []Analysis `json:"analyses,omitempty"`
	// A short analysis of a company
	ShortAnalyses []ShortAnalysis `json:"shortAnalyses,omitempty"`
	// Recent and upcoming trials for the company
	Trials             []Trial                    `json:"trials,omitempty"`
	Mortgages          *MortgagesRegistration     `json:"mortgages,omitempty"`
	CentralApproval    *CentralApproval           `json:"centralApproval,omitempty"`
	CorporateStructure *CorporateStructureSummary `json:"corporateStructure,omitempty"`
	// Displays listings on public stock exchanges
	PublicListings []PublicListing `json:"publicListings,omitempty"`
	KeyFigures     *KeyFigures     `json:"keyFigures,omitempty"`
	// Company business unit ID (DK only).
	BusinessUnitId string `json:"businessUnitId,omitempty"`
	// Company Id
	CompanyId string `json:"companyId,omitempty"`
	// Company main email.
	Email string `json:"email,omitempty"`
	// Established Date
	EstablishedDate string `json:"establishedDate,omitempty"`
	// Foundation Date
	FoundationDate string `json:"foundationDate,omitempty"`
	// The company's year of foundation.
	FoundationYear string `json:"foundationYear,omitempty"`
	// Liquidation Date
	LiquidationDate string `json:"liquidationDate,omitempty"`
	// Company main internet home page.
	HomePage string `json:"homePage,omitempty"`
	// Central Business Register (Denmark) marked company as protected against being contacted for advertisement purpose.  Applicable only for Denmark.
	MarketingProtection bool `json:"marketingProtection,omitempty"`
	// A list of NACE category information (code and name) that this company is associated with.
	NaceCategories []string `json:"naceCategories,omitempty"`
	// Company name.
	Name string `json:"name,omitempty"`
	// A textual description of the company's total number of employees. Might be a number, a range or a free form text.
	NumberOfEmployees string `json:"numberOfEmployees,omitempty"`
	// The minimum number of employees the company has. It may be the same as EmpMax if exact number is known.
	EmpMin int32 `json:"empMin,omitempty"`
	// The maximum number of employees the company has. It may be the same as EmpMin if exact number is known.
	EmpMax int32 `json:"empMax,omitempty"`
	// Company organisation number.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	// Company secret organisation number.  Companies may have a secret/private organisation number;  e.g. Swedish ENK.
	SOrganisationNumber string `json:"sOrganisationNumber,omitempty"`
	// The profit for this company.
	Profit string `json:"profit,omitempty"`
	// The revenue for this company.
	Revenue        string            `json:"revenue,omitempty"`
	Link           *Link             `json:"link,omitempty"`
	Location       *Location         `json:"location,omitempty"`
	PhoneNumbers   *TelephoneNumbers `json:"phoneNumbers,omitempty"`
	PostalAddress  *Address          `json:"postalAddress,omitempty"`
	Status         *Status           `json:"status,omitempty"`
	VisitorAddress *Address          `json:"visitorAddress,omitempty"`
	// Sector Code
	SectorCode string `json:"sectorCode,omitempty"`
	// Company purpose
	CompanyPurpose string `json:"companyPurpose,omitempty"`
}
