/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Summary of the corporate structure a company is part of.
type CorporateStructureSummary struct {
	Details *Link `json:"details,omitempty"`
	// Total number of companies that are part of the corporate structure.
	NumberOfCompanies int32 `json:"numberOfCompanies,omitempty"`
	// Number of direct subsidiaries of the current company.
	NumberOfSubsidiaries int32 `json:"numberOfSubsidiaries,omitempty"`
	// Name of the closest parent company.
	ParentCompanyName string `json:"parentCompanyName,omitempty"`
	// Organisation number of the closest parent company.
	ParentCompanyOrganisationNumber string `json:"parentCompanyOrganisationNumber,omitempty"`
	ParentCompanyLink *Link `json:"parentCompanyLink,omitempty"`
}
