/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff
import (
	"time"
)

// Represents a company or person share ownership.
type ShareholderEntity struct {
	// If this instance is a company, number of shareholders in current company.  Else, 0.
	Owners int32 `json:"owners,omitempty"`
	// If this instance is a company, number of indirect shareholders in current company.  Else, 0.
	IndirectOwners int32 `json:"indirectOwners,omitempty"`
	// Number of direct ownerships for this instance.
	Ownerships int32 `json:"ownerships,omitempty"`
	// Number of indirect ownerships for this instance.
	IndirectOwnerships int32 `json:"indirectOwnerships,omitempty"`
	// Shareholder-ID. Used when fetching more information for this shareholder.
	Id string `json:"id,omitempty"`
	// Organisation number. Only available for company shareholder.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	// Four-digit birth year. Only available for person shareholder.
	BirthYear string `json:"birthYear,omitempty"`
	// Only available for person shareholder.
	BirthDate time.Time `json:"birthDate,omitempty"`
	// Company- or person name.
	Name string `json:"name,omitempty"`
	// Shareholder address. E.g.: \"Drammensveien 1\"
	Address string `json:"address,omitempty"`
	// Shareholder postal code. E.g.: \"1234\"
	ZipCode string `json:"zipCode,omitempty"`
	// Shareholder city. E.g. \"OSLO\":
	Location string `json:"location,omitempty"`
	// Shareholder ISO2 country code. E.g.: \"NO\"
	Country string `json:"country,omitempty"`
	// Describes type of shareholder. [\"Person\" | \"Company\" | \"Unknown\"]
	EntityType string `json:"entityType,omitempty"`
}
