/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A paid product for this company.
type Product struct {
	// Content of the product.
	Content []string `json:"content,omitempty"`
	// The product name.
	Name string `json:"name,omitempty"`
}
