/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An Office of a company.
type Office struct {
	// Name of office.
	Name string `json:"name,omitempty"`
	// Type of office.
	Type_ string `json:"type,omitempty"`
	Address *Address `json:"address,omitempty"`
	Numbers *TelephoneNumbers `json:"numbers,omitempty"`
	OfficePostalAddress *Address `json:"officePostalAddress,omitempty"`
	OfficeVisitorAddress *Address `json:"officeVisitorAddress,omitempty"`
}
