/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

type AnalysisSection struct {
	AntallAnsatte int64 `json:"antallAnsatte,omitempty"`
	Loennskostnader int64 `json:"loennskostnader,omitempty"`
	AndreDriftskostnader int64 `json:"andreDriftskostnader,omitempty"`
	AvskrivingVarigeDriftsmidlerImEiend int64 `json:"avskrivingVarigeDriftsmidlerImEiend,omitempty"`
	SumDriftsinntekter int64 `json:"sumDriftsinntekter,omitempty"`
	Driftsresultat int64 `json:"driftsresultat,omitempty"`
	OrdinaertResultatFoerSkattekostnad int64 `json:"ordinaertResultatFoerSkattekostnad,omitempty"`
	OrdinaertResultat int64 `json:"ordinaertResultat,omitempty"`
	Aarsresultat int64 `json:"aarsresultat,omitempty"`
	SumAnleggsmidler int64 `json:"sumAnleggsmidler,omitempty"`
	SumOmloepsmidler int64 `json:"sumOmloepsmidler,omitempty"`
	SumEiendeler int64 `json:"sumEiendeler,omitempty"`
	SumEgenkapital int64 `json:"sumEgenkapital,omitempty"`
	SumKortsiktigGjeld int64 `json:"sumKortsiktigGjeld,omitempty"`
	SumLangsiktigGjeld int64 `json:"sumLangsiktigGjeld,omitempty"`
	SumEgenkapitalOgGjeld int64 `json:"sumEgenkapitalOgGjeld,omitempty"`
	Resultatgrad float64 `json:"resultatgrad,omitempty"`
	RentedeknGrad float64 `json:"rentedeknGrad,omitempty"`
	TotalrentabilitetLoennsomhet float64 `json:"totalrentabilitetLoennsomhet,omitempty"`
	EgenkapitalRentabilitetFoerSkatt float64 `json:"egenkapitalRentabilitetFoerSkatt,omitempty"`
	Egenkapitalandel float64 `json:"egenkapitalandel,omitempty"`
	Tapsbuffer float64 `json:"tapsbuffer,omitempty"`
	Likviditetsgrad float64 `json:"likviditetsgrad,omitempty"`
	Likviditetsgrad2 float64 `json:"likviditetsgrad2,omitempty"`
	Arbeidskapital int32 `json:"arbeidskapital,omitempty"`
	LangsiktigLagerfinansiering float64 `json:"langsiktigLagerfinansiering,omitempty"`
	Fremmedkapitalkostnad float64 `json:"fremmedkapitalkostnad,omitempty"`
	Gjeldsgrad float64 `json:"gjeldsgrad,omitempty"`
	GjennomsnittligLagertidDager float64 `json:"gjennomsnittligLagertidDager,omitempty"`
	GjennomsnittligKredittidForDebitorer float64 `json:"gjennomsnittligKredittidForDebitorer,omitempty"`
	GjennomsnittligKredittForLeverandoer float64 `json:"gjennomsnittligKredittForLeverandoer,omitempty"`
}
