/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Top turnover company in an industry
type TopTurnoverCompany struct {
	// Internal id of the company
	CompanyId string `json:"companyId,omitempty"`
	// Name of the company
	Name string `json:"name,omitempty"`
	// Turnover for the company, as an exact value, in the currency used by the country the industry resides in
	Turnover int64 `json:"turnover,omitempty"`
	// Year for which the values of this top company is valid. In standard ECS format.
	Year string `json:"year,omitempty"`
	Details *Link `json:"details,omitempty"`
}
