/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// The legal status of a company.
type Status struct {
	// A description of the status the company has in the business register.
	Description string `json:"description,omitempty"`
	// Register status flag for a company.  Possible values:  <value>ACTIVE</value><value>INACTIVE</value>
	StatusFlag string `json:"statusFlag,omitempty"`
}
