/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Represents a changed company.
type ChangedEntity struct {
	// Changed entity organisation number
	Id string `json:"id,omitempty"`
	// Patch object
	Patch *interface{} `json:"patch,omitempty"`
	// The time the change/patch was made, in milliseconds after 1970-01-01 00:00:00
	CreatedDate int64 `json:"createdDate,omitempty"`
	// Unique identifier of the change
	PatchId string `json:"patchId,omitempty"`
}
