/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A role a company has in a register company.
type RegisterCompanyRole struct {
	// The organisation number of the company that has this role.
	CompanyId string `json:"companyId,omitempty"`
	// The name of the entity that elected this role.
	Elector string `json:"elector,omitempty"`
	// The name of the entity that has this role.
	Name string `json:"name,omitempty"`
	// The responsibility of this role.
	Responsibility string `json:"responsibility,omitempty"`
	// The title of the role.
	Title string `json:"title,omitempty"`
	Details *Link `json:"details,omitempty"`
}
