/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Annual financial info for an attribute of an industry.
type FinancialInfo struct {
	// The code for the type of this account.
	Code string `json:"code,omitempty"`
	// The amount for this account.
	Amount string `json:"amount,omitempty"`
	// Year for this financial info. In standard ECS format.
	Year string `json:"year,omitempty"`
}
