/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff
import (
	"time"
)

// Details about a judicial trial
type Trial struct {
	// Date the trial was/will be held
	Scheduled time.Time `json:"scheduled,omitempty"`
	// Where the trial will take place
	Court string `json:"court,omitempty"`
	// Free text description the trial
	Summary string `json:"summary,omitempty"`
	// Free text description of parties involved
	Parties string `json:"parties,omitempty"`
	// A reference to the trial
	Reference string `json:"reference,omitempty"`
	// When the trial was registered
	Registered time.Time `json:"registered,omitempty"`
	// The type of the trial (typically 3 letter code like KON, TVI, ERS)
	Type_ string `json:"type,omitempty"`
	// Saksøker (Plaintiff) eller Saksøkt (Defendant)
	Role string `json:"role,omitempty"`
}
