/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// List of business person resources plus resource meta data, pagination and filter information.
type BusinessPersonList struct {
	// Professional with business roles in companies, and with connections to other professionals in the enterprise world. Roles can typically be: Chairman, committee member, deputy committee member or shareholder (Daglig Leder, Styreformann, Styremedlem, Varamedlem, Aksjon�r). A business connection is a connection this business person has to other businesses persons.
	BusinessPersons []BusinessPerson `json:"businessPersons,omitempty"`
	Sorting *Sorting `json:"sorting,omitempty"`
	// A possible rewrite of the query string made by the search engine. The search result typically reflects this  rewritten query
	CorrectedQuery string `json:"correctedQuery,omitempty"`
	// Total number of hits available.
	NumberOfHits int32 `json:"numberOfHits,omitempty"`
	// A set of related filters. The display name is a common description for all the filters in the group. I.e. if the display name in the filter group is: 'Countrypart' then you can expect all filters to represent a particular country part like: Nord-Norge (North of Norway) or Vestlandet.
	FilterGroups []FilterGroup `json:"filterGroups,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
