/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// Short comparison of company and industry on county- and country basis
type ShortAnalysis struct {
	AccountingYear int32 `json:"accountingYear,omitempty"`
	Konsern int32 `json:"konsern,omitempty"`
	AntallBedrifterBransjeFylke int32 `json:"antallBedrifterBransjeFylke,omitempty"`
	CompanyFigures *ShortAnalysisSection `json:"companyFigures,omitempty"`
	CountyFigures *ShortAnalysisSection `json:"countyFigures,omitempty"`
	CountryFigures *ShortAnalysisSection `json:"countryFigures,omitempty"`
	AsCountryFigures *ShortAnalysisSection `json:"asCountryFigures,omitempty"`
}
