/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An announcement from a company.
type Announcement struct {
	// The unique id of the announcement.
	Id string `json:"id,omitempty"`
	// The date of the announcement. Standard ECS format.
	Date string `json:"date,omitempty"`
	// The text of the announcement.
	Text string `json:"text,omitempty"`
	// The type (code) of the announcement.
	Type_ string `json:"type,omitempty"`
}
