/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff
import (
	"time"
)

type RoleEntryRealOwner struct {
	RoleTypeId string `json:"roleTypeId,omitempty"`
	RoleTypeName string `json:"roleTypeName,omitempty"`
	ElectedBy string `json:"electedBy,omitempty"`
	Responsibility string `json:"responsibility,omitempty"`
	LastUpdate time.Time `json:"lastUpdate,omitempty"`
}
