/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// List of EniroPro company adverts, plus resource meta data, pagination and filter information.
type EniroProCompanyList struct {
	// List of EniroPro companies
	Companies []EniroProCompany `json:"companies,omitempty"`
	// A possible rewrite of the query string made by the search engine. The search result typically reflects this  rewritten query
	CorrectedQuery string `json:"correctedQuery,omitempty"`
	// Total number of hits available.
	NumberOfHits int32 `json:"numberOfHits,omitempty"`
	// A set of related filters. The display name is a common description for all the filters in the group. I.e. if the display name in the filter group is: 'Countrypart' then you can expect all filters to represent a particular country part like: Nord-Norge (North of Norway) or Vestlandet.
	FilterGroups []FilterGroup `json:"filterGroups,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
