/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// An account used in company accounting
type Account struct {
	// The code for the type of this account.
	Code string `json:"code,omitempty"`
	// The amount for this account.
	Amount string `json:"amount,omitempty"`
}
