/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A company's phone numbers.
type TelephoneNumbers struct {
	// A company's fax number.
	FaxNumber string `json:"faxNumber,omitempty"`
	// A company's mobile phone number.
	MobilePhone string `json:"mobilePhone,omitempty"`
	// Additional mobile number of the company
	MobilePhone2 string `json:"mobilePhone2,omitempty"`
	// A company's telephone number.
	TelephoneNumber string `json:"telephoneNumber,omitempty"`
	// Additional telephone number of the company
	TelephoneNumber2 string `json:"telephoneNumber2,omitempty"`
}
