/*
 * Proff API
 *
 * You need a valid token to access Proff API. Contact sales for more information. Token header: Authorization : Token [YOUR_TOKEN]
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package proff

// A publicly registered company.
type RegisterCompany struct {
	// Company business unit ID (DK only).
	BusinessUnitId string `json:"businessUnitId,omitempty"`
	// Company Id
	CompanyId string `json:"companyId,omitempty"`
	// Company main email.
	Email string `json:"email,omitempty"`
	// Established Date
	EstablishedDate string `json:"establishedDate,omitempty"`
	// Foundation Date
	FoundationDate string `json:"foundationDate,omitempty"`
	// The company's year of foundation.
	FoundationYear string `json:"foundationYear,omitempty"`
	// Liquidation Date
	LiquidationDate string `json:"liquidationDate,omitempty"`
	// Company main internet home page.
	HomePage string `json:"homePage,omitempty"`
	// Central Business Register (Denmark) marked company as protected against being contacted for advertisement purpose.  Applicable only for Denmark.
	MarketingProtection bool `json:"marketingProtection,omitempty"`
	// A list of NACE category information (code and name) that this company is associated with.
	NaceCategories []string `json:"naceCategories,omitempty"`
	// Company name.
	Name string `json:"name,omitempty"`
	// A textual description of the company's total number of employees. Might be a number, a range or a free form text.
	NumberOfEmployees string `json:"numberOfEmployees,omitempty"`
	// The minimum number of employees the company has. It may be the same as EmpMax if exact number is known.
	EmpMin int32 `json:"empMin,omitempty"`
	// The maximum number of employees the company has. It may be the same as EmpMin if exact number is known.
	EmpMax int32 `json:"empMax,omitempty"`
	// Company organisation number.
	OrganisationNumber string `json:"organisationNumber,omitempty"`
	// Company secret organisation number.  Companies may have a secret/private organisation number;  e.g. Swedish ENK.
	SOrganisationNumber string `json:"sOrganisationNumber,omitempty"`
	// The profit for this company.
	Profit string `json:"profit,omitempty"`
	// The revenue for this company.
	Revenue string `json:"revenue,omitempty"`
	Link *Link `json:"link,omitempty"`
	Location *Location `json:"location,omitempty"`
	PhoneNumbers *TelephoneNumbers `json:"phoneNumbers,omitempty"`
	PostalAddress *Address `json:"postalAddress,omitempty"`
	Status *Status `json:"status,omitempty"`
	VisitorAddress *Address `json:"visitorAddress,omitempty"`
	// Sector Code
	SectorCode string `json:"sectorCode,omitempty"`
	// Company purpose
	CompanyPurpose string `json:"companyPurpose,omitempty"`
}
